development:
  adapter: postgresql
  database: cafehk_development
  encoding: unicode
  user: SzeChan 
  host: localhost
  pool: 5
  timeout: 5000


test:
  adapter: postgresql
  database: cafehk_test
  encoding: unicode
  user: SzeChan
  host: localhost
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: cafehk_production
  encoding: unicode
  pool: 5
  timeout: 5000